-- auto-generated definition
create table position_snapshot
(
    zcmc        varchar(200)    null comment '资产名称',
    zcdm        varchar(100)    null comment '资产代码',
    jydm        varchar(100)    null comment '交易代码',
    wstwd       varchar(100)    null comment '委受托维度',
    fzhwd       varchar(100)    null comment '账户维度',
    ztbh        varchar(100)    null comment '账套编号',
    jjztmc      varchar(200)    null comment '基金账套名称',
    fzztmc      varchar(200)    null comment '分组账套名称',
    zcdl        varchar(100)    null comment '资产大类',
    zcfl_1st    varchar(100)    null comment '资产分类一级',
    zcfl_2nd    varchar(100)    null comment '资产分类二级',
    zcfl_3rd    varchar(100)    null comment '资产分类三级',
    jycl        varchar(100)    null comment '交易策略',
    tzjl        varchar(100)    null comment '投资经理',
    zcfl        varchar(200)    null comment '资产分类',
    zxwbpj      varchar(100)    null comment '债项外部评级',
    kjfl        varchar(100)    null comment '会计分类',
    jjsz        decimal(32, 16) null comment '净价市值(亿)',
    yslxgl      decimal(32, 16) null comment '应收利息/股利(亿)',
    qjsz        decimal(32, 16) null comment '全价市值(亿)',
    pjye        decimal(32, 16) null comment '平均余额(亿)',
    pjye_rp     decimal(32, 16) null comment '日度平均余额(亿)',
    pjzjzy_bn   decimal(32, 16) null comment '平均资金占用（本年以来）(亿)',
    cwsy_bn     decimal(32, 16) null comment '财务收益（本年以来）(亿)',
    zhsy_bn     decimal(32, 16) null comment '综合收益（本年以来）(亿)',
    nhcwsyl_bn  decimal(32, 16) null comment '财务收益率（本年以来）',
    nhzhsyl_bn  decimal(32, 16) null comment '综合收益率（本年以来）',
    lxsr_bn     decimal(32, 16) null comment '利息收入（本年以来）(亿)',
    hlsr_bn     decimal(32, 16) null comment '红利收入（本年以来）(亿)',
    jcsr_bn     decimal(32, 16) null comment '价差收入（本年以来）(亿)',
    gyjzbdsy_bn decimal(32, 16) null comment '公允价值变动损益（本年以来）(亿)',
    qtzhsy_bn   decimal(32, 16) null comment '其他综合收益（本年以来）(亿)',
    qygjczjc_bn decimal(32, 16) null comment '权益工具处置价差（本年以来）(亿)',
    zcjzss_bn   decimal(32, 16) null comment '资产减值损失（本年以来）(亿)',
    zmye        decimal(32, 16) null comment '账面余额(亿)',
    hdsy_bn     decimal(32, 16) null comment '汇兑损益（本年以来）(亿)',
    jzzhsr_bn   decimal(32, 16) null comment '减值转回收入（本年以来）(亿)',
    jyfy_bn     decimal(32, 16) null comment '交易费用（本年以来）(亿)',
    lxzc_bn     decimal(32, 16) null comment '利息支出（本年以来）(亿)',
    qttzxgsz_bn decimal(32, 16) null comment '其他投资相关收支（本年以来）(亿)',
    pjzjzy_by   decimal(32, 16) null comment '平均资金占用（本月以来）(亿)',
    cwsy_by     decimal(32, 16) null comment '财务收益（本月以来）(亿)',
    zhsy_by     decimal(32, 16) null comment '综合收益（本月以来）(亿)',
    nhcwsyl_by  decimal(32, 16) null comment '财务收益率（本月以来）',
    nhzhsyl_by  decimal(32, 16) null comment '综合收益率（本月以来）',
    lxsr_by     decimal(32, 16) null comment '利息收入（本月以来）(亿)',
    hlsr_by     decimal(32, 16) null comment '红利收入（本月以来）(亿)',
    jcsr_by     decimal(32, 16) null comment '价差收入（本月以来）(亿)',
    gyjzbdsy_by decimal(32, 16) null comment '公允价值变动损益（本月以来）(亿)',
    qtzhsy_by   decimal(32, 16) null comment '其他综合收益（本月以来）(亿)',
    qygjczjc_by decimal(32, 16) null comment '权益工具处置价差（本月以来）(亿)',
    zcjzss_by   decimal(32, 16) null comment '资产减值损失（本月以来）(亿)',
    hdsy_by     decimal(32, 16) null comment '汇兑损益（本月以来）(亿)',
    jzzhsr_by   decimal(32, 16) null comment '减值转回收入（本月以来）(亿)',
    jyfy_by     decimal(32, 16) null comment '交易费用（本月以来）(亿)',
    lxzc_by     decimal(32, 16) null comment '利息支出（本月以来）(亿)',
    qttzxgsz_by decimal(32, 16) null comment '其他投资相关收支（本月以来）(亿)',
    ccsl        decimal(32, 16) null comment '持仓数量',
    cccb        decimal(32, 16) null comment '持仓成本',
    pmll        decimal(32, 16) null comment '票面利率',
    mrrq        varchar(20)     null comment '买入日期',
    scfxr       varchar(20)     null comment '首次付息日',
    dqr         varchar(20)     null comment '到期日',
    jq          decimal(32, 16) null comment '久期',
    dqsyl       decimal(32, 16) null comment '到期收益率',
    pmjz        decimal(32, 8)  null comment '票面价值',
    fxpl        varchar(20)     null comment '付息频率',
    ncsz        decimal(32, 16) null comment '年初市值(亿)',
    cccb_jg     decimal(32, 16) null comment '持仓成本(监管)(亿)',
    symye       decimal(32, 16) null comment '上月末余额(亿)',
    jzssye      decimal(32, 16) null comment '减值损失余额(亿)',
    uptm        datetime(6)     null comment '数据更新时间',
    p_dt        bigint          null comment '业务日期'
)
    comment '资产配置宽表' collate = utf8mb4_unicode_ci;
